name: School
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.41.2=h2797004_1
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=hd590300_3
  - pip=23.1.2=pyhd8ed1ab_0
  - python=3.11.3=h2755cc3_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cffi==1.15.1
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - fonttools==4.39.4
      - fqdn==1.5.1
      - idna==3.4
      - imageio==2.28.1
      - ipykernel==6.23.0
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.3
      - packaging==23.1
      - pandas==2.0.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.1
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.2
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tinycss2==1.2.1
      - tornado==6.3.2
      - traitlets==5.9.0
      - tzdata==2023.3
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - widgetsnbextension==4.0.7
prefix: /home/sofia/miniconda3/envs/School
